### ISSUE TITLE
Delete "Edit" function for Volunteers on the Pick Up Instruction and Delivery Instructions

### ISSUE THREAD

**Issue by thoughtsky** [factn/Resilience-Design#21]
As a volunteer, I want to be able to see all instructions from the organization and people in need, so that I always know where to pick up and drop off a box.

Right now the volunteer has the ability to edit the pick up and delivery instructions which might lead to confusion. This either is not necessary, as these informations are provided by the organisation and the person who ordered the box or the feature is just named wrong. 
This might need some input from someone who was around when the feature was designed and should be reviewed before deleting.

<img width="522" alt="grafik" src="https://user-images.githubusercontent.com/61591796/97545456-57619300-19cb-11eb-9cf9-888d5d80696c.png">

**Comment by karenkun** [comment]
@thoughtsky Here's a bit of context around the volunteer's ability to edit instructions:
So due to the nature of the mutual aid group where the organizer's role is in facilitating the tasks, the details of how that task gets completed is the volunteer's responsibility (since he/she is the person who will be doing it). So the ability to edit / update the instructions is to allow the volunteer to have more ownership over their task(s) without depending on the organizers themselves. (also sharing the burden of documentation/coordination between more people)

**Comment by thoughtsky** [comment]
Thank you for providing context on this! Absolutely makes sense. In this case I would say that this is good as is? I will put an appropriate label on it.
